/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package task1;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;

public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    private double[][] input;          //2D array to store coressponding time and paymnet
    private int nextID=-1;     // to input the time, payment combination to the next empty slot of the array
    private double currentMinWage=6.55; //current minimum wage
    private double[] sum;   //to calculate total minutes and total payment
    private double average=0;
    
    private void initVariables(){
        input=new double[10000][2];    //initialize array.assume that a user will not input(click the enter button) more than 10000 times
        sum=new double[2];              
         /**
         * sum[0] refers to the total number of minutes
         * sum[1] refers to the total amount of payments recieved
         */
        
        for(int row=0;row<10000;row++){                 //this nested loop sets every entry in input array to zero
            for(int column=0;column<2;column++){
                input[row][column]=0;
            }
        }
        sum[0]=0;   //total number of minutes zero initialy
        sum[1]=0;   //total payment is zero initialy
    }
    private void readMinWage(){     //prompt the user to input current minimum wage 
        try{
            String msg=JOptionPane.showInputDialog( "Enter Current Minimum Wage: $","6.55" );  //read input from message box
            currentMinWage=Double.parseDouble(msg);
        }catch(HeadlessException | NumberFormatException e){
            readMinWage();                  //prompt again if number format exception
        }catch(Exception e){
            System.exit(0);                 //exit system if cancel button is pressed
        }
    }
    public Menu() {
        initVariables();    //initiate class variables
        readMinWage();      //get user input for current min wage
        initComponents();   //initaite GUI components
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPrice = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        txtTime = new javax.swing.JFormattedTextField();
        txtPrice = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaReport = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnInput = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(400, 150, 0, 0));
        setResizable(false);

        lblPrice.setText("Payment for session in dollars and cents:");

        lblTime.setText("Tutoring time in minutes:");

        txtTime.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.0"))));
        txtTime.setText("0.0");
        txtTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimeActionPerformed(evt);
            }
        });

        txtPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        txtPrice.setText("0.0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTime)
                    .addComponent(lblPrice))
                .addGap(112, 112, 112)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTime, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(txtPrice))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblTime)
                        .addGap(18, 18, 18)
                        .addComponent(lblPrice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        txtAreaReport.setColumns(20);
        txtAreaReport.setEditable(false);
        txtAreaReport.setRows(5);
        jScrollPane1.setViewportView(txtAreaReport);

        btnInput.setText("Enter");
        btnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInputActionPerformed(evt);
            }
        });

        btnReport.setText("Run Report");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(btnQuit)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // quits the program when quit button is pressed
        System.exit(0);
        
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInputActionPerformed
        // TODO add your handling code here:
        double time=0;      //temporary variable to store next input
        double payment=0;   //temporary variable to store next input
        try{
            time=Double.parseDouble(txtTime.getText());       //read the text field dedicated to time and store time
            payment=Double.parseDouble(txtPrice.getText());      //read the text field dedicated to payment and store payment 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "invalid input");   //pop up message if input is not in correct format
            return;
        }
        if(time<=0 || time>240 || payment<=0 ){
            JOptionPane.showMessageDialog(null, "invalid input");   //pop up message if input doesn't meet given condition
            return;
        }
        
        nextID++;   //jump to the next empty slot of the input array
        input[nextID][0]=time;      //store time in column 1 of the array
        input[nextID][1]=payment;   //store paymnet in column 2 of the array
        
        JOptionPane.showMessageDialog(null, "Entry Added Successfully:\nTime:"+time+"\nPayment:"+payment); //input successfull
    }//GEN-LAST:event_btnInputActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // Generate report on click of run report button
        txtAreaReport.setText("");  //clear old report before new report is generated
        
        sum[0]=0;   //set total to zero because the loop does the summation everytime the button is pressed
        sum[1]=0;   //same as above
        
        for(int row=0;row<=nextID;row++){
            txtAreaReport.append("Minutes = "+input[row][0]+"\tEarnings = "+input[row][1]+"$\n");   //display the given inputs on the text Area
            for(int column=0;column<2;column++){
                sum[column]+=input[row][column];    //evaluates total number of minutes tutored and total payment
            }
        }
        average=sum[1]/(sum[0]/60); //average wage=total earnings/total time in hours
        
        txtAreaReport.append("\n\n**********************\n\nReport of your wages to Date:\n");    // just to adjust text order text area
        txtAreaReport.append("Total minutes spent tutoring = "+sum[0]+" minutes\n");//display total time in minutes text area
        txtAreaReport.append("Total Earnings = "+sum[1]+"$\n");//display total earnings text area
        txtAreaReport.append("Average per hour wage = "+average+"$\n");//display average wage on text area
        txtAreaReport.append("\nMinimum wage is currently $"+currentMinWage+"\n");//display current minimum wage
        
        
        /**
         * Append message to the text area depending on the relationship between the
         * calulated average and the current minimum wage
         */
        if(average<currentMinWage){
            txtAreaReport.append("\nyour wages per hour are below average");
        }
        else if(average>=currentMinWage && average<2*currentMinWage){
            txtAreaReport.append("\nyour wages per hour are on average");
        }
        else if(average>2*currentMinWage){
            txtAreaReport.append("\nYour wages per hour are above average");
        }
        else{
            txtAreaReport.append("\nNo input given ");
        }
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void txtTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimeActionPerformed

    
    /**
     * This method does the calculations to generate the report
     */
    private void calculate(){
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Menu().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInput;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnReport;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblTime;
    private javax.swing.JTextArea txtAreaReport;
    private javax.swing.JFormattedTextField txtPrice;
    private javax.swing.JFormattedTextField txtTime;
    // End of variables declaration//GEN-END:variables
}
